### ISSUE TITLE
hydra.errors.ConfigCompositionException: Could not override 'common_eval.path'.

### ISSUE THREAD

**Issue by EricLina** [ictnlp/MoE-Waitk#1]
I followed the Readme's guidance , and excuse the train command , 
```
expert_lagging=1,3,5,7,9,11,13,15
python train.py  --ddp-backend=no_c10d ${data} --arch transformer --share-all-embeddings \
 --optimizer adam \
 --adam-betas '(0.9, 0.98)' \
 --clip-norm 0.0 \
 --lr 5e-4 \
 --lr-scheduler inverse_sqrt \
 --warmup-init-lr 1e-07 \
 --warmup-updates 4000 \
 --dropout 0.3 \
 --criterion label_smoothed_cross_entropy \
 --reset-dataloader --reset-lr-scheduler --reset-optimizer\
 --label-smoothing 0.1 \
 --encoder-attention-heads 8 \
 --decoder-attention-heads 8 \
 --left-pad-source False \
 --fp16 \
 --equal-weight \
 --expert-lagging ${expert_lagging} \
 --save-dir ${modelfile}/$Prefix \
 --max-tokens 4096 --update-freq 1 
```
**But unluckily it failed because of  : **hydra.errors.ConfigCompositionException: Could not override 'common_eval.path'.** . 
I thought it is hydra's version problem and installed it again , but it still did not work.**

**I don't know whether it is a bug , and I was trying to fix it but not successed . Could you help to take a look at it ? @Vily1998**

The full error log shows as below .
>anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/hydra/experimental/initialize.py:36: UserWarning: hydra.experimental.initialize() is no longer experimental. Use hydra.initialize()
  message="hydra.experimental.initialize() is no longer experimental."
anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/hydra/experimental/compose.py:19: UserWarning: hydra.experimental.compose() is no longer experimental. Use hydra.compose()
  message="hydra.experimental.compose() is no longer experimental."
anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/hydra/core/default_element.py:126: UserWarning: In 'config': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  See {url} for more information"""
anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config': Defaults list is missing `_self_`. See https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/hydra/core/default_element.py:126: UserWarning: In 'lr_scheduler/inverse_sqrt': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  See {url} for more information"""
anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/hydra/core/default_element.py:126: UserWarning: In 'optimizer/adam': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  See {url} for more information"""
anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/hydra/core/default_element.py:126: UserWarning: In 'task/language_modeling': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  See {url} for more information"""
Traceback (most recent call last):
  File "anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 378, in _apply_overrides_to_config
    OmegaConf.update(cfg, key, value, merge=True)
  File "anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/omegaconf/omegaconf.py", line 725, in update
    root[key_] = {}
  File "anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 311, in __setitem__
    key=key, value=value, type_override=ConfigKeyError, cause=e
  File "anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/omegaconf/base.py", line 196, in _format_and_raise
    type_override=type_override,
  File "anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/omegaconf/_utils.py", line 741, in format_and_raise
    _raise(ex, cause)
  File "anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 308, in __setitem__
    self.__set_impl(key=key, value=value)
  File "anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 318, in __set_impl
    self._set_item_impl(key, value)
  File "anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 511, in _set_item_impl
    self._validate_set(key, value)
  File "anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 180, in _validate_set
    target = self._get_node(key) if key is not None else self
  File "anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 465, in _get_node
    self._validate_get(key)
  File "anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 167, in _validate_get
    key=key, value=value, cause=ConfigAttributeError(msg)
  File "anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/omegaconf/base.py", line 196, in _format_and_raise
    type_override=type_override,
  File "anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/omegaconf/_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigKeyError: Key 'common_eval' is not in struct
    full_key: common_eval
    object_type=dict

>The above exception was the direct cause of the following exception:

>Traceback (most recent call last):
  File "train.py", line 14, in <module>
    cli_main()
  File "Moe-waitk/MoE-Waitk/fairseq_cli/train.py", line 395, in cli_main
    cfg = convert_namespace_to_omegaconf(args)
  File "Moe-waitk/MoE-Waitk/fairseq/dataclass/utils.py", line 285, in convert_namespace_to_omegaconf
    composed_cfg = compose(cfg_name, overrides=overrides, strict=False)
  File "anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/hydra/experimental/compose.py", line 26, in compose
    strict=strict,
  File "anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/hydra/compose.py", line 38, in compose
    with_log_configuration=False,
  File "anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 563, in compose_config
    from_shell=from_shell,
  File "anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 145, in load_configuration
    from_shell=from_shell,
  File "anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 262, in _load_configuration_impl
    ConfigLoaderImpl._apply_overrides_to_config(config_overrides, cfg)
  File "anaconda3/envs/torch_moewaitk/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 383, in _apply_overrides_to_config
    ) from ex
hydra.errors.ConfigCompositionException: Could not override 'common_eval.path'.
To append to your config use +common_eval.path=null

**Comment by zhangshaolei1998** [comment]
After checking, MoE Wait-k is properly trained using the script we provided. 
Please check whether your environment is suitable or whether the compilation is successful.

**Comment by EricLina** [comment]
Fine , I find out the reason .
In the default setting , the lagging should be set as 1,3,5,7,9,11,13,15  which is fixed, but I set it by myself (1,3,5,7) so the error occured.

By the way , If I want to using the lagging settiing by myself such as 1,3,5,7 , What should I do ?

**Comment by EricLina** [comment]
@Vily1998

**Comment by zhangshaolei1998** [comment]
> Fine , I find out the reason . In the default setting , the lagging should be set as 1,3,5,7,9,11,13,15 which is fixed, but I set it by myself (1,3,5,7) so the error occured.
> 
> By the way , If I want to using the lagging settiing by myself such as 1,3,5,7 , What should I do ?

You should ensure that the length of set expert lagging is equal to the number of attention heads in Transformer.
If you want to set expert lagging to 1,3,5,7, you should apply a Transformer-Small with 4 heads.

**Comment by EricLina** [comment]
I tried to reproduce it on the other machine using the right lagging commond , but  still get the same error. 
Later , I found the actual reason for the error : The version of  moegaconf and hydra-core is too high !
So I lowerd them to 
> omegaconf                 2.0.6   
> hydra-core                1.0.7     
 
And the problem solved.

**Comment by EricLina** [comment]
> > Fine , I find out the reason . In the default setting , the lagging should be set as 1,3,5,7,9,11,13,15 which is fixed, but I set it by myself (1,3,5,7) so the error occured.
> > By the way , If I want to using the lagging settiing by myself such as 1,3,5,7 , What should I do ?
> 
> You should ensure that the length of set expert lagging is equal to the number of attention heads in Transformer. If you want to set expert lagging to 1,3,5,7, you should apply a Transformer-Small with 4 heads.

Thank you @Vily1998 
If I set the lagging as 3,3,3,3 ,Is the effect similar to waitk=3?

**Comment by zhangshaolei1998** [comment]
> > > Fine , I find out the reason . In the default setting , the lagging should be set as 1,3,5,7,9,11,13,15 which is fixed, but I set it by myself (1,3,5,7) so the error occured.
> > > By the way , If I want to using the lagging settiing by myself such as 1,3,5,7 , What should I do ?
> > 
> > 
> > You should ensure that the length of set expert lagging is equal to the number of attention heads in Transformer. If you want to set expert lagging to 1,3,5,7, you should apply a Transformer-Small with 4 heads.
> 
> Thank you @Vily1998 If I set the lagging as 3,3,3,3 ,Is the effect similar to waitk=3?

No, because our method employs multipath training.

**Comment by EricLina** [comment]
Got it .Thank you
